<%
booly_env = ->(value) {
  return false if value.blank?

  return true if (['0', 't', 'true'].include?(value.to_s.downcase))
  return false
}
%>

development:
  secret_key_base: 9ac2d0ad8ebcc312090e99d745006d3cf8
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  revrise_token: 38ab45b8-9c1c-4fb6-9a8a-9ad9bded0cfe
  facebook_app_id: 699594440130491
  google_analytics_id: UA-11425486-8
  google_conversion_id: 123123123
  google_conversion_label: testtesttest
  mixpanel_token: 62afe04b1dfdaaf7f4e8f9ed751db125
  mixpanel_id: 503597
  kommed_client_id: <%= ENV["KOMMED_CLIENT_ID"] %>
  docraptor_test_mode: true
  docraptor_api_key: <%= ENV["DOCRAPTOR_API_KEY"] %>
  swish_key_password: <%= ENV["SWISH_KEY_PASSWORD"] || "swish" %>
  swish_callback_url: <%= ENV["SWISH_CALLBACK_URL"] %>
  ping_kommed: <%= booly_env.(ENV['PING_KOMMED']) || false %>
test:
  secret_key_base: a1580ad61ccb6ac60f9f256948cf63d6e20
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  revrise_token: 38ab45b8-9c1c-4fb6-9a8a-9ad9bded0cfe
  facebook_app_id: 699594440130491
  google_analytics_id: UA-11425486-8
  google_conversion_id: 123123123
  google_conversion_label: testtesttest
  mixpanel_token: 62afe04b1dfdaaf7f4e8f9ed751db125
  mixpanel_id: 503597
  kommed_client_id: <%= ENV["KOMMED_CLIENT_ID"] %>
  docraptor_test_mode: true
  docraptor_api_key: <%= ENV["DOCRAPTOR_API_KEY"] %>
  swish_key_password: <%= ENV["SWISH_KEY_PASSWORD"] || "swish" %>
  swish_callback_url: <%= ENV["SWISH_CALLBACK_URL"] %>
  ping_kommed: <%= booly_env.(ENV['PING_KOMMED']) || false %>
staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sidekiq_redis_url: <%= ENV['SIDEKIQ_REDIS_URL'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  google_analytics_id: UA-11425486-8
  google_conversion_id: 123123123
  google_conversion_label: testtesttest
  mixpanel_token: 62afe04b1dfdaaf7f4e8f9ed751db125
  mixpanel_id: 503597
  kommed_client_id: <%= ENV["KOMMED_CLIENT_ID"] %>
  docraptor_test_mode: true
  docraptor_api_key: <%= ENV["DOCRAPTOR_API_KEY"] %>
  swish_key_password: <%= ENV["SWISH_KEY_PASSWORD"] %>
  swish_callback_url: <%= ENV["SWISH_CALLBACK_URL"] %>
  ping_kommed: <%= booly_env.(ENV['PING_KOMMED']) || false %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV['STRIPE_PUBLISHABLE_KEY'] %>
  stripe_secret_key: <%= ENV['STRIPE_SECRET_KEY'] %>
  sendgrid_username: <%= ENV['SENDGRID_USERNAME'] %>
  sendgrid_password: <%= ENV['SENDGRID_PASSWORD'] %>
  sidekiq_redis_url: <%= ENV['SIDEKIQ_REDIS_URL'] %>
  mailer_default_host: <%= ENV['MAILER_DEFAULT_HOST'] %>
  revrise_token: 9bff5f0c-e886-4041-9c28-c9eb46f57c4d
  facebook_app_id: 699578733465395
  google_analytics_id: UA-11878155-4
  google_conversion_id: 1021084733
  google_conversion_label: jPEvCKeAr1sQvYjy5gM
  mixpanel_token: 6f1a0c17d2e14e994e234ac9b81987ab
  mixpanel_id: 471579
  kommed_client_id: <%= ENV["KOMMED_CLIENT_ID"] %>
  docraptor_test_mode: <%= ENV["DOCRAPTOR_TEST_MODE"] == "true" %>
  docraptor_api_key: <%= ENV["DOCRAPTOR_API_KEY"] %>
  swish_key_password: <%= ENV["SWISH_KEY_PASSWORD"] %>
  swish_callback_url: <%= ENV["SWISH_CALLBACK_URL"] || 'https://gavoshop.wateraid.se/callbacks/swish' %>
  ping_kommed: <%= booly_env.(ENV['PING_KOMMED']) || false %>
